//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapUtility.UserSessionServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Infolog", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Infolog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapUtility.UserSessionServiceReference.InfologEntry[] EntriesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapUtility.UserSessionServiceReference.InfologEntry[] Entries {
            get {
                return this.EntriesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntriesField, value) != true)) {
                    this.EntriesField = value;
                    this.RaisePropertyChanged("Entries");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologEntry", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class InfologEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapUtility.UserSessionServiceReference.InfologType TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapUtility.UserSessionServiceReference.InfologType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologType", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    public enum InfologType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class Fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((this.RequestIdField.Equals(value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessControlledItemKey", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class AccessControlledItemKey : SoapUtility.UserSessionServiceReference.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapUtility.UserSessionServiceReference.AccessControlledType ItemTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubItemNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapUtility.UserSessionServiceReference.AccessControlledType ItemType {
            get {
                return this.ItemTypeField;
            }
            set {
                if ((this.ItemTypeField.Equals(value) != true)) {
                    this.ItemTypeField = value;
                    this.RaisePropertyChanged("ItemType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubItemName {
            get {
                return this.SubItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubItemNameField, value) != true)) {
                    this.SubItemNameField = value;
                    this.RaisePropertyChanged("SubItemName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProxyBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.KernelInterop")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.UserSessionServiceReference.XppObjectBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.UserSessionServiceReference.UserSessionInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.UserSessionServiceReference.CurrencyInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.UserSessionServiceReference.AccessControlledItemKey))]
    public partial class ProxyBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.UserSessionServiceReference.UserSessionInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.UserSessionServiceReference.CurrencyInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SoapUtility.UserSessionServiceReference.AccessControlledItemKey))]
    public partial class XppObjectBase : SoapUtility.UserSessionServiceReference.ProxyBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSessionInfo", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class UserSessionInfo : SoapUtility.UserSessionServiceReference.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AOSLocaleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AXLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapUtility.UserSessionServiceReference.Timezone CompanyTimeZoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapUtility.UserSessionServiceReference.CurrencyInfo CurrencyInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSysAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapUtility.UserSessionServiceReference.PreferredCalendar UserPreferredCalendarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SoapUtility.UserSessionServiceReference.Timezone UserPreferredTimeZoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AOSLocaleName {
            get {
                return this.AOSLocaleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AOSLocaleNameField, value) != true)) {
                    this.AOSLocaleNameField = value;
                    this.RaisePropertyChanged("AOSLocaleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AXLanguage {
            get {
                return this.AXLanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.AXLanguageField, value) != true)) {
                    this.AXLanguageField = value;
                    this.RaisePropertyChanged("AXLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapUtility.UserSessionServiceReference.Timezone CompanyTimeZone {
            get {
                return this.CompanyTimeZoneField;
            }
            set {
                if ((this.CompanyTimeZoneField.Equals(value) != true)) {
                    this.CompanyTimeZoneField = value;
                    this.RaisePropertyChanged("CompanyTimeZone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapUtility.UserSessionServiceReference.CurrencyInfo CurrencyInfo {
            get {
                return this.CurrencyInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyInfoField, value) != true)) {
                    this.CurrencyInfoField = value;
                    this.RaisePropertyChanged("CurrencyInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSysAdmin {
            get {
                return this.IsSysAdminField;
            }
            set {
                if ((this.IsSysAdminField.Equals(value) != true)) {
                    this.IsSysAdminField = value;
                    this.RaisePropertyChanged("IsSysAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapUtility.UserSessionServiceReference.PreferredCalendar UserPreferredCalendar {
            get {
                return this.UserPreferredCalendarField;
            }
            set {
                if ((this.UserPreferredCalendarField.Equals(value) != true)) {
                    this.UserPreferredCalendarField = value;
                    this.RaisePropertyChanged("UserPreferredCalendar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SoapUtility.UserSessionServiceReference.Timezone UserPreferredTimeZone {
            get {
                return this.UserPreferredTimeZoneField;
            }
            set {
                if ((this.UserPreferredTimeZoneField.Equals(value) != true)) {
                    this.UserPreferredTimeZoneField = value;
                    this.RaisePropertyChanged("UserPreferredTimeZone");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyInfo", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    [System.SerializableAttribute()]
    public partial class CurrencyInfo : SoapUtility.UserSessionServiceReference.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ExchangeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISOCurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuffixField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyCode {
            get {
                return this.CurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyCodeField, value) != true)) {
                    this.CurrencyCodeField = value;
                    this.RaisePropertyChanged("CurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ExchangeRate {
            get {
                return this.ExchangeRateField;
            }
            set {
                if ((this.ExchangeRateField.Equals(value) != true)) {
                    this.ExchangeRateField = value;
                    this.RaisePropertyChanged("ExchangeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISOCurrencyCode {
            get {
                return this.ISOCurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ISOCurrencyCodeField, value) != true)) {
                    this.ISOCurrencyCodeField = value;
                    this.RaisePropertyChanged("ISOCurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefix {
            get {
                return this.PrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefixField, value) != true)) {
                    this.PrefixField = value;
                    this.RaisePropertyChanged("Prefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suffix {
            get {
                return this.SuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.SuffixField, value) != true)) {
                    this.SuffixField = value;
                    this.RaisePropertyChanged("Suffix");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessControlledType", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public enum AccessControlledType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MenuItemDisplay = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MenuItemOutput = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MenuItemAction = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebUrlItem = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebActionItem = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WebManagedContentItem = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Table = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TableField = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Timezone", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public enum Timezone : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS1200INTERNATIONALDATELINEWEST = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS1100COORDINATEDUNIVERSALTIME = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS1100MIDWAYISLAND_SAMOA = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS1000HAWAII = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0900ALASKA = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0800PACIFICTIME = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0800TIJUANA_BAJACALIFORNIA = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0700ARIZONA = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0700MOUNTAINTIME = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0700CHIHUAHUA_LAPAZ_MAZATLAN = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0600CENTRALAMERICA = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0600CENTRALTIME = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0600GUADALAJARA_MEXICOCITY = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0600SASKATCHEWAN = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0500BOGOTA_LIMA_QUITO_RIOBRANCO = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0500EASTERNTIME = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0500INDIANA = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0400ASUNCION = 95,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0400ATLANTICTIME = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0400LAPAZ = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0400MANAUS = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0400SANTIAGO = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0430CARACAS = 85,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0330NEWFOUNDLAND = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0300_SALVADOR = 87,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0300BRASILIA = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0300BUENOSAIRES = 86,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0300BUENOSAIRES_GEORGETOWN = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0300GREENLAND = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0300MONTEVIDEO = 83,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0200MIDATLANTIC = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0100AZORES = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTMINUS0100CAPEVERDIS = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_CASABLANCA = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_CASABLANCA_MONTROVIA_REYKJAVIK = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_COORDINATEDUNIVERSALTIME = 89,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_DUBLIN_EDINBURGH_LISBON_LONDON = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMT_PLUS0300KALININGRAD_MINSK = 90,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0100_AMSTERDAM_BERLIN_BERN_ROME = 79,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0100BELGRADE_BRATISLAVA_BUDAPEST = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0100BRUSSELS_COPENHAGEN_MADRID = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0100SARAJEVO_SKOPJE_WARSAW_ZAGREB = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0100TRIPOLI = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0100WESTCENTRALAFRICA = 78,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200_DAMASCUS = 96,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200AMMAN = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200ATHENS_BUCHAREST_ISTANBUL = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200BEIRUT = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200MINSK = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200CAIRO = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200HARARE_PRETORIA = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200HELSINKI_KYIV_RIGA_VILNIUS = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200ISTANBUL = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200JERUSALEM = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0200WINDHOEK = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0300BAGHDAD = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0300KUWAIT_RIYADH = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0300MOSCOW_STPETERSBURG_VOLGOGRAD = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0300NAIROBI = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0300TBILISI = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0330TEHRAN = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0400ABUDHABI_MUSCAT = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0400BAKU = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0400IZHEVSK_SAMARA = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0400CAUCASUSSTANDARDTIME = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0400PORTLOUIS = 92,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0400YEREVAN = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0430KABUL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0500EKATERINBURG = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0500ISLAMABAD_KARACHI = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0500ISLAMABAD_KARACHI_TASHKENT = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0530CHENNAI_KOLKATA_MUMBAI = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0530SRIJAYAWARDENEPURA = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0545KATHMANDU = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0600ALMATY_NOVOSIBIRSK = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0600ASTANA_DHAKA = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0600DHAKA = 88,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0600MAGADAN = 91,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0630_YANGON = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0700_BANGKOK_HANOI_JAKARTA = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0700KRASNOYARSK = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0800_ULAANBAATAR = 97,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0800BEIJING_CHONGQING_HONGKONG = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0800IRKUTSK_ULAANBATAAR = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0800KUALALUMPUR_SINGAPORE = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0800PERTH = 77,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0800TAIPEI = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0900OSAKA_SAPPORO_TOKYO = 72,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0900SEOUL = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0900YAKUTSK = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0930ADELAIDE = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS0930DARWIN = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1000BRISBANE = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1000CANBERRA_MELBOURNE_SYDNEY = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1000GUAM_PORTMORESBY = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1000HOBART = 71,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1000VLADIVOSTOK = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1100CHOKURDAKH = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1100MAGADAN_SOLOMONIS = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1200ANADYR_PETRO_KAMCHATSKY = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1200AUCKLAND_WELLINGTON = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1200COORDINATEDUNIVERSALTIME = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1200FIJI_KAMCHATKA_MARSHALLIS = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMTPLUS1300NUKU_ALOFA = 73,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreferredCalendar", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public enum PreferredCalendar : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gregorian = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hijri = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UmAlQura = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessRight", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.AX.Application")]
    public enum AccessRight : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoAccess = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        View = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Edit = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Add = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Correction = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", ConfigurationName="UserSessionServiceReference.UserSessionService")]
    public interface UserSessionService {
        
        // CODEGEN: Generating message contract since message ApplyTimeZone has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/ApplyTi" +
            "meZone", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/ApplyTi" +
            "meZoneResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.UserSessionServiceReference.Fault), Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.UserSessionServiceReference.ApplyTimeZoneResponse ApplyTimeZone(SoapUtility.UserSessionServiceReference.ApplyTimeZone request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/ApplyTi" +
            "meZone", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/ApplyTi" +
            "meZoneResponse")]
        System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.ApplyTimeZoneResponse> ApplyTimeZoneAsync(SoapUtility.UserSessionServiceReference.ApplyTimeZone request);
        
        // CODEGEN: Generating message contract since message GetAccessRights has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetAcce" +
            "ssRights", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetAcce" +
            "ssRightsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.UserSessionServiceReference.Fault), Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.UserSessionServiceReference.GetAccessRightsResponse GetAccessRights(SoapUtility.UserSessionServiceReference.GetAccessRights request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetAcce" +
            "ssRights", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetAcce" +
            "ssRightsResponse")]
        System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.GetAccessRightsResponse> GetAccessRightsAsync(SoapUtility.UserSessionServiceReference.GetAccessRights request);
        
        // CODEGEN: Generating message contract since message GetPartitionKey has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetPart" +
            "itionKey", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetPart" +
            "itionKeyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.UserSessionServiceReference.Fault), Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.UserSessionServiceReference.GetPartitionKeyResponse GetPartitionKey(SoapUtility.UserSessionServiceReference.GetPartitionKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetPart" +
            "itionKey", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetPart" +
            "itionKeyResponse")]
        System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.GetPartitionKeyResponse> GetPartitionKeyAsync(SoapUtility.UserSessionServiceReference.GetPartitionKey request);
        
        // CODEGEN: Generating message contract since message GetPartitionKeysForUser has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetPart" +
            "itionKeysForUser", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetPart" +
            "itionKeysForUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.UserSessionServiceReference.Fault), Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.UserSessionServiceReference.GetPartitionKeysForUserResponse GetPartitionKeysForUser(SoapUtility.UserSessionServiceReference.GetPartitionKeysForUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetPart" +
            "itionKeysForUser", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetPart" +
            "itionKeysForUserResponse")]
        System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.GetPartitionKeysForUserResponse> GetPartitionKeysForUserAsync(SoapUtility.UserSessionServiceReference.GetPartitionKeysForUser request);
        
        // CODEGEN: Generating message contract since message GetUserSessionInfo has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetUser" +
            "SessionInfo", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetUser" +
            "SessionInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.UserSessionServiceReference.Fault), Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.UserSessionServiceReference.GetUserSessionInfoResponse GetUserSessionInfo(SoapUtility.UserSessionServiceReference.GetUserSessionInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetUser" +
            "SessionInfo", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/GetUser" +
            "SessionInfoResponse")]
        System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.GetUserSessionInfoResponse> GetUserSessionInfoAsync(SoapUtility.UserSessionServiceReference.GetUserSessionInfo request);
        
        // CODEGEN: Generating message contract since message IsSinglePartitionSystem has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/IsSingl" +
            "ePartitionSystem", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/IsSingl" +
            "ePartitionSystemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.UserSessionServiceReference.Fault), Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.UserSessionServiceReference.IsSinglePartitionSystemResponse IsSinglePartitionSystem(SoapUtility.UserSessionServiceReference.IsSinglePartitionSystem request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/IsSingl" +
            "ePartitionSystem", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/IsSingl" +
            "ePartitionSystemResponse")]
        System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.IsSinglePartitionSystemResponse> IsSinglePartitionSystemAsync(SoapUtility.UserSessionServiceReference.IsSinglePartitionSystem request);
        
        // CODEGEN: Generating message contract since message RemoveTimeZone has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/RemoveT" +
            "imeZone", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/RemoveT" +
            "imeZoneResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoapUtility.UserSessionServiceReference.Fault), Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/Fault", Name="Fault", Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        SoapUtility.UserSessionServiceReference.RemoveTimeZoneResponse RemoveTimeZone(SoapUtility.UserSessionServiceReference.RemoveTimeZone request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/RemoveT" +
            "imeZone", ReplyAction="http://schemas.microsoft.com/dynamics/2011/01/services/UserSessionService/RemoveT" +
            "imeZoneResponse")]
        System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.RemoveTimeZoneResponse> RemoveTimeZoneAsync(SoapUtility.UserSessionServiceReference.RemoveTimeZone request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApplyTimeZone", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class ApplyTimeZone {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.UserSessionServiceReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public System.DateTime dateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=1)]
        public int timeZoneOffset;
        
        public ApplyTimeZone() {
        }
        
        public ApplyTimeZone(SoapUtility.UserSessionServiceReference.CallContext CallContext, System.DateTime dateTime, int timeZoneOffset) {
            this.CallContext = CallContext;
            this.dateTime = dateTime;
            this.timeZoneOffset = timeZoneOffset;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ApplyTimeZoneResponse", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class ApplyTimeZoneResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.UserSessionServiceReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public System.DateTime result;
        
        public ApplyTimeZoneResponse() {
        }
        
        public ApplyTimeZoneResponse(SoapUtility.UserSessionServiceReference.Infolog Infolog, System.DateTime result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccessRights", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class GetAccessRights {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.UserSessionServiceReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public SoapUtility.UserSessionServiceReference.AccessControlledItemKey[] _keys;
        
        public GetAccessRights() {
        }
        
        public GetAccessRights(SoapUtility.UserSessionServiceReference.CallContext CallContext, SoapUtility.UserSessionServiceReference.AccessControlledItemKey[] _keys) {
            this.CallContext = CallContext;
            this._keys = _keys;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccessRightsResponse", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class GetAccessRightsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.UserSessionServiceReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public SoapUtility.UserSessionServiceReference.AccessRight[] result;
        
        public GetAccessRightsResponse() {
        }
        
        public GetAccessRightsResponse(SoapUtility.UserSessionServiceReference.Infolog Infolog, SoapUtility.UserSessionServiceReference.AccessRight[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPartitionKey", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class GetPartitionKey {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.UserSessionServiceReference.CallContext CallContext;
        
        public GetPartitionKey() {
        }
        
        public GetPartitionKey(SoapUtility.UserSessionServiceReference.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPartitionKeyResponse", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class GetPartitionKeyResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.UserSessionServiceReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public string result;
        
        public GetPartitionKeyResponse() {
        }
        
        public GetPartitionKeyResponse(SoapUtility.UserSessionServiceReference.Infolog Infolog, string result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPartitionKeysForUser", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class GetPartitionKeysForUser {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.UserSessionServiceReference.CallContext CallContext;
        
        public GetPartitionKeysForUser() {
        }
        
        public GetPartitionKeysForUser(SoapUtility.UserSessionServiceReference.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPartitionKeysForUserResponse", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class GetPartitionKeysForUserResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.UserSessionServiceReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public string[] result;
        
        public GetPartitionKeysForUserResponse() {
        }
        
        public GetPartitionKeysForUserResponse(SoapUtility.UserSessionServiceReference.Infolog Infolog, string[] result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserSessionInfo", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class GetUserSessionInfo {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.UserSessionServiceReference.CallContext CallContext;
        
        public GetUserSessionInfo() {
        }
        
        public GetUserSessionInfo(SoapUtility.UserSessionServiceReference.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserSessionInfoResponse", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class GetUserSessionInfoResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.UserSessionServiceReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public SoapUtility.UserSessionServiceReference.UserSessionInfo result;
        
        public GetUserSessionInfoResponse() {
        }
        
        public GetUserSessionInfoResponse(SoapUtility.UserSessionServiceReference.Infolog Infolog, SoapUtility.UserSessionServiceReference.UserSessionInfo result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsSinglePartitionSystem", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class IsSinglePartitionSystem {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.UserSessionServiceReference.CallContext CallContext;
        
        public IsSinglePartitionSystem() {
        }
        
        public IsSinglePartitionSystem(SoapUtility.UserSessionServiceReference.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsSinglePartitionSystemResponse", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class IsSinglePartitionSystemResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.UserSessionServiceReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public bool result;
        
        public IsSinglePartitionSystemResponse() {
        }
        
        public IsSinglePartitionSystemResponse(SoapUtility.UserSessionServiceReference.Infolog Infolog, bool result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveTimeZone", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class RemoveTimeZone {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.UserSessionServiceReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public System.DateTime dateTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=1)]
        public int timeZoneOffset;
        
        public RemoveTimeZone() {
        }
        
        public RemoveTimeZone(SoapUtility.UserSessionServiceReference.CallContext CallContext, System.DateTime dateTime, int timeZoneOffset) {
            this.CallContext = CallContext;
            this.dateTime = dateTime;
            this.timeZoneOffset = timeZoneOffset;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveTimeZoneResponse", WrapperNamespace="http://schemas.microsoft.com/dynamics/2011/01/services", IsWrapped=true)]
    public partial class RemoveTimeZoneResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2013/01/datacontracts")]
        public SoapUtility.UserSessionServiceReference.Infolog Infolog;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/dynamics/2011/01/services", Order=0)]
        public System.DateTime result;
        
        public RemoveTimeZoneResponse() {
        }
        
        public RemoveTimeZoneResponse(SoapUtility.UserSessionServiceReference.Infolog Infolog, System.DateTime result) {
            this.Infolog = Infolog;
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserSessionServiceChannel : SoapUtility.UserSessionServiceReference.UserSessionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserSessionServiceClient : System.ServiceModel.ClientBase<SoapUtility.UserSessionServiceReference.UserSessionService>, SoapUtility.UserSessionServiceReference.UserSessionService {
        
        public UserSessionServiceClient() {
        }
        
        public UserSessionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserSessionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserSessionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserSessionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.UserSessionServiceReference.ApplyTimeZoneResponse SoapUtility.UserSessionServiceReference.UserSessionService.ApplyTimeZone(SoapUtility.UserSessionServiceReference.ApplyTimeZone request) {
            return base.Channel.ApplyTimeZone(request);
        }
        
        public SoapUtility.UserSessionServiceReference.Infolog ApplyTimeZone(SoapUtility.UserSessionServiceReference.CallContext CallContext, System.DateTime dateTime, int timeZoneOffset, out System.DateTime result) {
            SoapUtility.UserSessionServiceReference.ApplyTimeZone inValue = new SoapUtility.UserSessionServiceReference.ApplyTimeZone();
            inValue.CallContext = CallContext;
            inValue.dateTime = dateTime;
            inValue.timeZoneOffset = timeZoneOffset;
            SoapUtility.UserSessionServiceReference.ApplyTimeZoneResponse retVal = ((SoapUtility.UserSessionServiceReference.UserSessionService)(this)).ApplyTimeZone(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.ApplyTimeZoneResponse> SoapUtility.UserSessionServiceReference.UserSessionService.ApplyTimeZoneAsync(SoapUtility.UserSessionServiceReference.ApplyTimeZone request) {
            return base.Channel.ApplyTimeZoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.ApplyTimeZoneResponse> ApplyTimeZoneAsync(SoapUtility.UserSessionServiceReference.CallContext CallContext, System.DateTime dateTime, int timeZoneOffset) {
            SoapUtility.UserSessionServiceReference.ApplyTimeZone inValue = new SoapUtility.UserSessionServiceReference.ApplyTimeZone();
            inValue.CallContext = CallContext;
            inValue.dateTime = dateTime;
            inValue.timeZoneOffset = timeZoneOffset;
            return ((SoapUtility.UserSessionServiceReference.UserSessionService)(this)).ApplyTimeZoneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.UserSessionServiceReference.GetAccessRightsResponse SoapUtility.UserSessionServiceReference.UserSessionService.GetAccessRights(SoapUtility.UserSessionServiceReference.GetAccessRights request) {
            return base.Channel.GetAccessRights(request);
        }
        
        public SoapUtility.UserSessionServiceReference.Infolog GetAccessRights(SoapUtility.UserSessionServiceReference.CallContext CallContext, SoapUtility.UserSessionServiceReference.AccessControlledItemKey[] _keys, out SoapUtility.UserSessionServiceReference.AccessRight[] result) {
            SoapUtility.UserSessionServiceReference.GetAccessRights inValue = new SoapUtility.UserSessionServiceReference.GetAccessRights();
            inValue.CallContext = CallContext;
            inValue._keys = _keys;
            SoapUtility.UserSessionServiceReference.GetAccessRightsResponse retVal = ((SoapUtility.UserSessionServiceReference.UserSessionService)(this)).GetAccessRights(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.GetAccessRightsResponse> SoapUtility.UserSessionServiceReference.UserSessionService.GetAccessRightsAsync(SoapUtility.UserSessionServiceReference.GetAccessRights request) {
            return base.Channel.GetAccessRightsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.GetAccessRightsResponse> GetAccessRightsAsync(SoapUtility.UserSessionServiceReference.CallContext CallContext, SoapUtility.UserSessionServiceReference.AccessControlledItemKey[] _keys) {
            SoapUtility.UserSessionServiceReference.GetAccessRights inValue = new SoapUtility.UserSessionServiceReference.GetAccessRights();
            inValue.CallContext = CallContext;
            inValue._keys = _keys;
            return ((SoapUtility.UserSessionServiceReference.UserSessionService)(this)).GetAccessRightsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.UserSessionServiceReference.GetPartitionKeyResponse SoapUtility.UserSessionServiceReference.UserSessionService.GetPartitionKey(SoapUtility.UserSessionServiceReference.GetPartitionKey request) {
            return base.Channel.GetPartitionKey(request);
        }
        
        public SoapUtility.UserSessionServiceReference.Infolog GetPartitionKey(SoapUtility.UserSessionServiceReference.CallContext CallContext, out string result) {
            SoapUtility.UserSessionServiceReference.GetPartitionKey inValue = new SoapUtility.UserSessionServiceReference.GetPartitionKey();
            inValue.CallContext = CallContext;
            SoapUtility.UserSessionServiceReference.GetPartitionKeyResponse retVal = ((SoapUtility.UserSessionServiceReference.UserSessionService)(this)).GetPartitionKey(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.GetPartitionKeyResponse> SoapUtility.UserSessionServiceReference.UserSessionService.GetPartitionKeyAsync(SoapUtility.UserSessionServiceReference.GetPartitionKey request) {
            return base.Channel.GetPartitionKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.GetPartitionKeyResponse> GetPartitionKeyAsync(SoapUtility.UserSessionServiceReference.CallContext CallContext) {
            SoapUtility.UserSessionServiceReference.GetPartitionKey inValue = new SoapUtility.UserSessionServiceReference.GetPartitionKey();
            inValue.CallContext = CallContext;
            return ((SoapUtility.UserSessionServiceReference.UserSessionService)(this)).GetPartitionKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.UserSessionServiceReference.GetPartitionKeysForUserResponse SoapUtility.UserSessionServiceReference.UserSessionService.GetPartitionKeysForUser(SoapUtility.UserSessionServiceReference.GetPartitionKeysForUser request) {
            return base.Channel.GetPartitionKeysForUser(request);
        }
        
        public SoapUtility.UserSessionServiceReference.Infolog GetPartitionKeysForUser(SoapUtility.UserSessionServiceReference.CallContext CallContext, out string[] result) {
            SoapUtility.UserSessionServiceReference.GetPartitionKeysForUser inValue = new SoapUtility.UserSessionServiceReference.GetPartitionKeysForUser();
            inValue.CallContext = CallContext;
            SoapUtility.UserSessionServiceReference.GetPartitionKeysForUserResponse retVal = ((SoapUtility.UserSessionServiceReference.UserSessionService)(this)).GetPartitionKeysForUser(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.GetPartitionKeysForUserResponse> SoapUtility.UserSessionServiceReference.UserSessionService.GetPartitionKeysForUserAsync(SoapUtility.UserSessionServiceReference.GetPartitionKeysForUser request) {
            return base.Channel.GetPartitionKeysForUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.GetPartitionKeysForUserResponse> GetPartitionKeysForUserAsync(SoapUtility.UserSessionServiceReference.CallContext CallContext) {
            SoapUtility.UserSessionServiceReference.GetPartitionKeysForUser inValue = new SoapUtility.UserSessionServiceReference.GetPartitionKeysForUser();
            inValue.CallContext = CallContext;
            return ((SoapUtility.UserSessionServiceReference.UserSessionService)(this)).GetPartitionKeysForUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.UserSessionServiceReference.GetUserSessionInfoResponse SoapUtility.UserSessionServiceReference.UserSessionService.GetUserSessionInfo(SoapUtility.UserSessionServiceReference.GetUserSessionInfo request) {
            return base.Channel.GetUserSessionInfo(request);
        }
        
        public SoapUtility.UserSessionServiceReference.Infolog GetUserSessionInfo(SoapUtility.UserSessionServiceReference.CallContext CallContext, out SoapUtility.UserSessionServiceReference.UserSessionInfo result) {
            SoapUtility.UserSessionServiceReference.GetUserSessionInfo inValue = new SoapUtility.UserSessionServiceReference.GetUserSessionInfo();
            inValue.CallContext = CallContext;
            SoapUtility.UserSessionServiceReference.GetUserSessionInfoResponse retVal = ((SoapUtility.UserSessionServiceReference.UserSessionService)(this)).GetUserSessionInfo(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.GetUserSessionInfoResponse> SoapUtility.UserSessionServiceReference.UserSessionService.GetUserSessionInfoAsync(SoapUtility.UserSessionServiceReference.GetUserSessionInfo request) {
            return base.Channel.GetUserSessionInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.GetUserSessionInfoResponse> GetUserSessionInfoAsync(SoapUtility.UserSessionServiceReference.CallContext CallContext) {
            SoapUtility.UserSessionServiceReference.GetUserSessionInfo inValue = new SoapUtility.UserSessionServiceReference.GetUserSessionInfo();
            inValue.CallContext = CallContext;
            return ((SoapUtility.UserSessionServiceReference.UserSessionService)(this)).GetUserSessionInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.UserSessionServiceReference.IsSinglePartitionSystemResponse SoapUtility.UserSessionServiceReference.UserSessionService.IsSinglePartitionSystem(SoapUtility.UserSessionServiceReference.IsSinglePartitionSystem request) {
            return base.Channel.IsSinglePartitionSystem(request);
        }
        
        public SoapUtility.UserSessionServiceReference.Infolog IsSinglePartitionSystem(SoapUtility.UserSessionServiceReference.CallContext CallContext, out bool result) {
            SoapUtility.UserSessionServiceReference.IsSinglePartitionSystem inValue = new SoapUtility.UserSessionServiceReference.IsSinglePartitionSystem();
            inValue.CallContext = CallContext;
            SoapUtility.UserSessionServiceReference.IsSinglePartitionSystemResponse retVal = ((SoapUtility.UserSessionServiceReference.UserSessionService)(this)).IsSinglePartitionSystem(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.IsSinglePartitionSystemResponse> SoapUtility.UserSessionServiceReference.UserSessionService.IsSinglePartitionSystemAsync(SoapUtility.UserSessionServiceReference.IsSinglePartitionSystem request) {
            return base.Channel.IsSinglePartitionSystemAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.IsSinglePartitionSystemResponse> IsSinglePartitionSystemAsync(SoapUtility.UserSessionServiceReference.CallContext CallContext) {
            SoapUtility.UserSessionServiceReference.IsSinglePartitionSystem inValue = new SoapUtility.UserSessionServiceReference.IsSinglePartitionSystem();
            inValue.CallContext = CallContext;
            return ((SoapUtility.UserSessionServiceReference.UserSessionService)(this)).IsSinglePartitionSystemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapUtility.UserSessionServiceReference.RemoveTimeZoneResponse SoapUtility.UserSessionServiceReference.UserSessionService.RemoveTimeZone(SoapUtility.UserSessionServiceReference.RemoveTimeZone request) {
            return base.Channel.RemoveTimeZone(request);
        }
        
        public SoapUtility.UserSessionServiceReference.Infolog RemoveTimeZone(SoapUtility.UserSessionServiceReference.CallContext CallContext, System.DateTime dateTime, int timeZoneOffset, out System.DateTime result) {
            SoapUtility.UserSessionServiceReference.RemoveTimeZone inValue = new SoapUtility.UserSessionServiceReference.RemoveTimeZone();
            inValue.CallContext = CallContext;
            inValue.dateTime = dateTime;
            inValue.timeZoneOffset = timeZoneOffset;
            SoapUtility.UserSessionServiceReference.RemoveTimeZoneResponse retVal = ((SoapUtility.UserSessionServiceReference.UserSessionService)(this)).RemoveTimeZone(inValue);
            result = retVal.result;
            return retVal.Infolog;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.RemoveTimeZoneResponse> SoapUtility.UserSessionServiceReference.UserSessionService.RemoveTimeZoneAsync(SoapUtility.UserSessionServiceReference.RemoveTimeZone request) {
            return base.Channel.RemoveTimeZoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapUtility.UserSessionServiceReference.RemoveTimeZoneResponse> RemoveTimeZoneAsync(SoapUtility.UserSessionServiceReference.CallContext CallContext, System.DateTime dateTime, int timeZoneOffset) {
            SoapUtility.UserSessionServiceReference.RemoveTimeZone inValue = new SoapUtility.UserSessionServiceReference.RemoveTimeZone();
            inValue.CallContext = CallContext;
            inValue.dateTime = dateTime;
            inValue.timeZoneOffset = timeZoneOffset;
            return ((SoapUtility.UserSessionServiceReference.UserSessionService)(this)).RemoveTimeZoneAsync(inValue);
        }
    }
}
